### ISSUE TITLE
QA 수정할 내용

### ISSUE THREAD

**Issue by boring-km** [yeolsimee/MoneySaving-Android#40]
## TODO

- [x] 카테고리 수정 화면 sub text 없애기
- [x] 카테고리 수정 후 홈화면으로 돌아오면 루틴 조회정보 업데이트
- [x] 내정보에서 카테고리수정창에 있는 상태로 홈으로 돌아가서 카테고리추가를하면 내정보로 다시 돌아오면 카테고리 수정창이 떠있어 추가된 카테고리가 실시간 반영이안됨
- [x] 카테고리 삭제를 한 루틴을 클릭시 수정하기 창이 뜨는데 데이터들이 하나도 없는 수정하기 창이뜨고 상단 뒤로가기도 안먹힘
- [x] 하단 gnb 활성화 이미지 교체 요청 현재 루틴추천, 내정보 활성화 아이콘이 더 굵어서 똑같이 교체 필요 (디자인팀 작업필요)
- [x] 알림이 on이 안되는건지 시각적으로만 상태가 안바뀌는건지 몰겠는데 알림이 이상해요 알림이 비활성화 되어있어 누르면 알림이 설정됐다는 토스트메시지는 뜸근데 라디오버튼 상태가 안바뀜
- [x] 루틴명 말줄임은 적용됐는데 체크영역이 없음
