### ISSUE TITLE
리팩토링 및 문구 변경

### ISSUE THREAD

**Issue by boring-km** [yeolsimee/MoneySaving-Android#48]
## TODO

- [x] 일부 벡터 이미지 PNG로 변경 (화면 로딩 시 렌더링 느려져서 간혹 안보이는 이미지들 있음)
- [x] "알람"으로 보이는 문구 "알림" 으로 수정
- [x] 카테고리 수정 화면에서 카테고리 하나 삭제 하면 무조건 비어있는 이미지 나오는 현상 있음
- [x] 홈화면에서 오늘 날짜 판단이 잘 안되어서 수정 불가 팝업 뜨는 현상 간혹 있음
- [x] 내 정보 알림 상태를 앱 권한 상태에 맞춰서 보이도록 하기
- [x] 회원탈퇴 후 로그인 화면으로 이동하지 않음
